version: '3.2'
services:
  kernelMS:
    container_name: 'kernelMS'
    build:
      context: .
      dockerfile: Dockerfile
    image: base
    volumes:
      - ./MS_CUDA:/MS_CUDA
    stdin_open: true
    tty: true
    ipc: 'host'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIESA=all
      - nvcc-arch=sm_52 -v -Xcompiler="-pthread"